from typing import Callable, TypeVar, ParamSpec

P = ParamSpec("P")
R = TypeVar("R")

def log(msg: str | None = None, success_msg: str | None = None, failed_msg: str | None = None) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
def timeit(func: Callable[P, R]) -> Callable[P, R]: ...
def memoize(func: Callable[P, R]) -> Callable[P, R]: ...
def validate(condition: Callable[..., bool],) -> Callable[[Callable[P, R]], Callable[P, R]]: ...